name:                kaleidoscope
version:             0.1.0.0
github:              "dvaneson/kaleidoscope"
license:             BSD3
author:              "Donovan Ellison"
maintainer:          "dvaneson@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Compilers

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dvaneson/kaleidoscope#readme>

dependencies:
- base >= 4.7 && < 5
- parsec >= 3.1
- haskeline >= 0.7.1.2
- mtl >= 2.1.3
- llvm-hs == 6.0.0
- llvm-hs-pure == 6.0.0
- containers >= 0.4
- bytestring >= 0.10.8.1
- transformers >= 0.5.2.0


library:
  source-dirs: src
  c-sources: cbits/putchard.c

executables:
  ks:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -optl
    - -rdynamic
    dependencies:
    - kaleidoscope

tests:
  kaleidoscope-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kaleidoscope
